goog.addDependency("../../../../scripts/app.js", ['Avisky.App'], ['Avisky.GpsPopoverViewDelegate']);
goog.addDependency("../../../../scripts/as_gps.js", ['Avisky.GpsPopoverViewDelegate'], []);
goog.addDependency("../../../../scripts/as_gps.js", ['Avisky.GpsButtonView'], []);
goog.addDependency("../../../../scripts/as_status.js", ['Avisky.FlightStatusPopoverViewDelegate'], []);
goog.addDependency("../../../../scripts/as_status.js", ['Avisky.FlightStatusButtonView'], []);
goog.addDependency("../../../../scripts/bing.js", [], []);
goog.addDependency("../../../../scripts/bluemarble.js", [], []);
goog.addDependency("../../../../scripts/modestmaps.js", [], []);
goog.addDependency("../../../../scripts/popoverview.js", ['Avisky.PopoverView', 'Avisky.SelectionModel'], []);
goog.addDependency("../../../../scripts/as_radiopop.js", ['Avisky.RadioButtonPopoverView'], []);
